changelog:
  categories:
    - title: "✨ 새 기능"
      labels:
        - feature
    - title: "🐛 버그 수정"
      labels:
        - bug
    - title: "📚 문서"
      labels:
        - documentation
    - title: "🛠️ 유지보수"
      labels:
        - maintenance
    - title: "기타 변경"
      labels:
        - "*"
